name: Github Actions 실행

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm i

      - name: 빌드
        run: npm run build

      - name: 빌드 결과 확인
        run: |
          echo "현재 디렉토리:"
          ls
          echo "-----------------------"
          echo "dist 디렉토리:"
          cd dist
          ls

      - name: AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일들 전체 삭제
        run: aws s3 rm --recursive s3://gamebalancer

      - name: S3에 빌드된 파일 업로드하기
        run: aws s3 cp ./dist s3://gamebalancer --recursive

      - name: Cloudfront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E2K9M1GX25W7R1 --paths "/*"
